spring:
  application:
    name: app1
  profiles: app1
server:
  port: 8081
---
spring:
  application:
    name: app2
  profiles: app2
server:
  port: 8070
---
spring:
  application:
    name: app3
  profiles: app3
server:
  port: 8071
