spring:
  profiles: app1
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: app2
server:
  port: 8082
---
spring:
  profiles: app3
server:
  port: 8083
